# See available versions in https://docs.rke2.io/release-notes/v1.34.X
rke2_version: v1.34.7+rke2r1

rke2_token: "{{ k8s_bootstrap_token }}"
rke2_first_master: "{{ groups['k8s_master_nodes'][0] }}"
rke2_type: "{{ (inventory_hostname in groups['k8s_master_nodes']) | ternary('server', 'agent') }}"

# Cilium is configured with WireGuard encryption in files/rke2-cilium-config.yaml.
rke2_cni: cilium

# Must not overlap with the nodes' WireGuard IPs or cloud internal network.
rke2_cluster_cidr: 172.16.0.0/16
rke2_service_cidr: 172.17.0.0/16
rke2_cluster_dns: 172.17.0.10

rke2_config_dir: /etc/rancher/rke2
rke2_data_dir: /var/lib/rancher/rke2
rke2_bin_dir: /var/lib/rancher/rke2/bin
rke2_kubeconfig: /etc/rancher/rke2/rke2.yaml

wireguard_interface: wg0
wireguard_network: "172.31.0.0/24"
wireguard_port: 51820
wireguard_mtu: 1420
wireguard_persistent_keepalive: 25
wireguard_key_dir: /etc/wireguard

ntp_server: pool.ntp.org
