---
# See available versions in https://github.com/controlplaneio-fluxcd/flux-operator/releases
flux_operator_version: "0.53.0"

# See available versions in https://github.com/fluxcd/flux2/releases
flux_instance_version: "2.8.x"

flux_gitops_repo_url: ssh://git@github.com/nathansiegfrid/k8s-gitops.git
flux_gitops_ref: refs/heads/main
flux_gitops_path: clusters/home
flux_deploy_key: "{{ vault_flux_deploy_key | default('') }}"
flux_deploy_key_pub: "{{ vault_flux_deploy_key_pub | default('') }}"
