---
- name: Confirm cluster destruction
  ansible.builtin.pause:
    prompt:
      "DANGER: This will PERMANENTLY DESTROY the cluster on all nodes. Type
      'destroy-cluster' to proceed"
  register: confirmation
  run_once: true

- name: Assert user confirmation
  ansible.builtin.assert:
    that:
      - confirmation.user_input == "destroy-cluster"
    fail_msg: "Cluster destruction aborted."
    success_msg: "Cluster destruction confirmed."
  run_once: true

- name: Run RKE2 uninstall script
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2-uninstall.sh
  when: not ansible_check_mode
  failed_when: false
