---
- name: Setup RKE2 nodes
  hosts: k8s_nodes
  become: true
  vars:
    ansible_user: "{{ ssh_user }}"

  environment:
    PATH: "{{ rke2_bin_dir }}:{{ ansible_env.PATH }}"
    KUBECONFIG: "{{ rke2_kubeconfig }}"

  tasks:
    - name: Create RKE2 data directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ rke2_data_dir }}"

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0700"
      loop:
        - "{{ rke2_config_dir }}"
        - "{{ rke2_data_dir }}/agent/etc/kubelet.conf.d"

    - name: Create required master node directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0700"
      when: rke2_type == 'server'
      loop:
        - "{{ rke2_data_dir }}/server/manifests"
        - /var/log/kubernetes

    - name: Write RKE2 config
      ansible.builtin.template:
        src: rke2-config.yaml.j2
        dest: "{{ rke2_config_dir }}/config.yaml"
        owner: root
        group: root
        mode: "0600"

    - name: Write kubelet drop-in config
      ansible.builtin.copy:
        src: kubelet-config.yaml
        dest: "{{ rke2_data_dir }}/agent/etc/kubelet.conf.d/99-custom.yaml"
        owner: root
        group: root
        mode: "0600"

    - name: Write audit policy
      ansible.builtin.copy:
        src: audit-policy.yaml
        dest: "{{ rke2_config_dir }}/audit-policy.yaml"
        owner: root
        group: root
        mode: "0600"
      when: rke2_type == 'server'

    - name: Write Cilium HelmChartConfig
      ansible.builtin.copy:
        src: rke2-cilium-config.yaml
        dest: "{{ rke2_data_dir }}/server/manifests/rke2-cilium-config.yaml"
        owner: root
        group: root
        mode: "0600"
      when: rke2_type == 'server'

    - name: Install RKE2
      ansible.builtin.shell:
        cmd: curl -sfL https://get.rke2.io | sh -
      environment:
        INSTALL_RKE2_VERSION: "{{ rke2_version }}"
        INSTALL_RKE2_TYPE: "{{ rke2_type }}"
      args:
        creates: /usr/local/bin/rke2
      when: not ansible_check_mode

    - name: Start RKE2 service on first master node
      ansible.builtin.systemd_service:
        name: rke2-server
        state: started
        enabled: true
        daemon_reload: true
      when: inventory_hostname == rke2_first_master

    - name: Wait for API server on first master node
      ansible.builtin.wait_for:
        host: "{{ wireguard_ip }}"
        port: 6443
        sleep: 10
        timeout: 300
      when: inventory_hostname == rke2_first_master

    - name: Start RKE2 service on remaining master nodes
      ansible.builtin.systemd_service:
        name: rke2-server
        state: started
        enabled: true
        daemon_reload: true
      when:
        - rke2_type == 'server'
        - inventory_hostname != rke2_first_master

    - name: Wait for API server on remaining master nodes
      ansible.builtin.wait_for:
        host: "{{ wireguard_ip }}"
        port: 6443
        sleep: 10
        timeout: 300
      when:
        - rke2_type == 'server'
        - inventory_hostname != rke2_first_master

    - name: Start RKE2 service on worker nodes
      ansible.builtin.systemd_service:
        name: rke2-agent
        state: started
        enabled: true
        daemon_reload: true
      when: rke2_type == 'agent'

    - name: Wait for Ready status
      ansible.builtin.command:
        cmd: >
          kubectl get node {{ inventory_hostname }} -o
          jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
      when: not ansible_check_mode
      delegate_to: "{{ rke2_first_master if rke2_type == 'agent' else inventory_hostname }}"
      register: node_ready
      delay: 10
      retries: 30
      until: node_ready.stdout == "True"
      changed_when: false

    - name: Add kubectl to path
      ansible.builtin.copy:
        content: |
          export PATH=$PATH:{{ rke2_bin_dir }}
        dest: /etc/profile.d/rke2.sh
        owner: root
        group: root
        mode: "0644"
      when: rke2_type == 'server'

    - name: Create user kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"
      when: rke2_type == 'server'

    - name: Write user kubeconfig file
      ansible.builtin.copy:
        src: "{{ rke2_kubeconfig }}"
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
      when: rke2_type == 'server'

    - name: Get node status
      ansible.builtin.command:
        cmd: kubectl get nodes -o wide
      when: not ansible_check_mode
      delegate_to: "{{ rke2_first_master }}"
      register: node_status
      changed_when: false
      run_once: true

    - name: Print node status
      ansible.builtin.debug:
        msg: "{{ node_status.stdout_lines }}"
      run_once: true
