---
- name: Install RKE2
  hosts: k8s_nodes
  become: true

  vars:
    ansible_host: "{{ node_private_ip }}"
    ansible_user: "{{ ssh_user }}"

  tasks:
    - name: Install RKE2
      include_role:
        name: rke2_cis
      vars:
        rke2_action: install
