---
- name: Setup RKE2 clients
  hosts: k8s_master_nodes
  gather_facts: false
  become: true

  vars:
    ansible_host: "{{ node_private_ip }}"
    ansible_user: "{{ ssh_user }}"
    rke2_bin_dir: /var/lib/rancher/rke2/bin
    rke2_kubeconfig: /etc/rancher/rke2/rke2.yaml

  tasks:
    - name: Check if RKE2 is installed
      ansible.builtin.stat:
        path: "{{ rke2_kubeconfig }}"
      register: rke2_kubeconfig_file

    - name: Assert RKE2 is installed
      ansible.builtin.assert:
        that: rke2_kubeconfig_file.stat.exists
        fail_msg: "RKE2 is not installed on this node. Please run the RKE2 installation playbook first."

    - name: Symlink RKE2 binaries to /usr/local/bin
      ansible.builtin.file:
        src: "{{ rke2_bin_dir }}/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        state: link
        force: true
      loop:
        - kubectl
        - crictl
        - ctr

    - name: Create user kube directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Write user kubeconfig file
      ansible.builtin.copy:
        src: "{{ rke2_kubeconfig }}"
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Check if Helm is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/helm
      register: helm_binary

    - name: Download Helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: "0700"
      when: not helm_binary.stat.exists

    - name: Install Helm
      ansible.builtin.command:
        cmd: /tmp/get-helm-3
      when: not helm_binary.stat.exists
