---
rke2_type: server

# See available versions in https://docs.rke2.io/release-notes/v1.34.X
rke2_version: v1.34.7+rke2r1
rke2_psa_enforce_version: "v1.34"

rke2_cni: none
rke2_disable_kube_proxy: true
rke2_disable_components:
  - rke2-ingress-nginx

# Must not overlap with the nodes' private IPs or cloud internal network.
rke2_cluster_cidr: 10.42.0.0/16
rke2_service_cidr: 10.43.0.0/16
rke2_cluster_dns: 10.43.0.10

rke2_config_dir: /etc/rancher/rke2
rke2_data_dir: /var/lib/rancher/rke2
rke2_bin_dir: /var/lib/rancher/rke2/bin
rke2_kubeconfig: /etc/rancher/rke2/rke2.yaml

reboot_required: false

etcd_restore_log: /tmp/rke2-restore.log
etcd_restore_timeout_seconds: 120
