---
rke2_type: server

rke2_server_token: ""
rke2_agent_token: ""

# See available versions in https://docs.rke2.io/release-notes/v1.34.X
rke2_version: v1.34.7+rke2r1
rke2_psa_enforce_version: "v1.34"

rke2_cni: none
rke2_ingress_controller: none
rke2_disable_kube_proxy: true
rke2_disable_components: []

# Must not overlap with the nodes' private IPs or cloud internal network.
rke2_cluster_cidr: 10.42.0.0/16
rke2_service_cidr: 10.43.0.0/16
rke2_cluster_dns: 10.43.0.10

rke2_config_dir: /etc/rancher/rke2
rke2_data_dir: /var/lib/rancher/rke2
rke2_bin_dir: /var/lib/rancher/rke2/bin
rke2_kubeconfig: /etc/rancher/rke2/rke2.yaml

etcd_s3: false
etcd_s3_bucket: ""
etcd_s3_region: ""
etcd_s3_endpoint: "s3.amazonaws.com"
etcd_s3_access_key: ""
etcd_s3_secret_key: ""

etcd_snapshot_name: ""
etcd_restore_log: /tmp/rke2-restore.log
etcd_restore_timeout_seconds: 120
